spring.application.name=ecommerce-backend

# DATABASE CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=root

razorpay.key.id=YOUR_KEY
razorpay.key.secret=YOUR_SECRET

# JPA CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SERVER PORT
server.port=8080